
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS whatsapp TEXT;

ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS labor_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS parts_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_type TEXT NOT NULL DEFAULT 'valor',
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS diagram_marks JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS converted_order_id UUID REFERENCES public.service_orders(id) ON DELETE SET NULL;
