// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
    // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
        import.meta.env.VITE_SUPABASE_URL ||
        (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined);

  // Support both PUBLISHABLE_KEY (Lovable convention) and ANON_KEY (Supabase convention)
  const SUPABASE_PUBLISHABLE_KEY =
        import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
        import.meta.env.VITE_SUPABASE_ANON_KEY ||
        (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined) ||
        (typeof process !== 'undefined' ? process.env.SUPABASE_ANON_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
        const missing = [
                ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
                ...(!SUPABASE_PUBLISHABLE_KEY
                            ? ['VITE_SUPABASE_PUBLISHABLE_KEY (ou VITE_SUPABASE_ANON_KEY)']
                            : []),
              ];
        const message = `[ERRO DE CONFIGURACAO] Variaveis de ambiente Supabase ausentes na Vercel: ${missing.join(', ')}. Acesse Vercel > funilariaab > Environment Variables e adicione as variaveis faltantes.`;
        console.error(`[Supabase] ${message}`);
        throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
                storage: typeof window !== 'undefined' ? window.localStorage : undefined,
                autoRefreshToken: true,
                persistSession: true,
                detectSessionInUrl: true,
        },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
    get(_, prop, receiver) {
          if (!_supabase) _supabase = createSupabaseClient();
          return Reflect.get(_supabase, prop, receiver);
    },
});
